### ISSUE TITLE
Pa11y 4.0

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#159]
Pa11y 4.0 should be along soon. There are just a few issues we'd like to resolve before we set an end-of-support date for 3.x:

  - [x] #137 Allow Reporter Options for JavaScript Interface (Added in `3.8.0`)
  - [x] #142 pa11y and HTMLcodesniffer giving different results (Documented)
  - [x] #146 CLI hide-elements option not working as expected (PR opened: #160)
  - [x] #153 Processing thousands of URLs (Added in `3.8.0`)

Pa11y 4.0 will include no breaking changes except that support for Node.js 0.12 will be dropped. Pa11y 3.x _may_ include an extended end-of-support date (beyond our usual 6 months) because we'll be using it in the dashboard/webservice for some time.
